workflows:
  ios-app-store:
    name: iOS App Store
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.alp.indirimRadari
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)   # Codemagic'e gir
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FCI_BUILD_DIR/ios/Pods
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS release
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true
