name: indirim_radari
description: "İndirim Kapısı - Market Kampanyaları"
publish_to: 'none'
version: 1.0.1+83

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  flutter_local_notifications: ^17.2.0
  shared_preferences: ^2.3.0
  intl: any
  google_mobile_ads: ^5.3.0
  app_tracking_transparency: ^2.0.6+1
  http: ^1.2.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/ustbanner.jpeg
    - assets/guncelustbanner.jpeg
    - assets/ikon.jpg
    - assets/logo.jpeg
    - assets/adi-registration.properties
    - assets/agent.jpeg
    - assets/agent_gri.jpeg
    - assets/robot.jpeg
    - assets/guncelrobot.jpeg
    - assets/acilis.jpeg
